# Site settings

author :
  name : Andrey Amelin
  email : droboshok@ua.fm
  github : droboshok
  twitter : droboshok
  facebook : droboshok




markdown: kramdown




exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md","node_modules", "gulpfile.js", "PR.sublime-project","Gemfile", "Gemfile.lock", "_config.yml"]
highlighter: pygments






